### ISSUE TITLE
error: no available ip in list

### ISSUE THREAD

**Issue by weihanmatt** [rinkky/xbox-download-host#4]
大佬 
一直显示filter ip list...
最后来了一个 error: no available ip in list

**Comment by rinkky** [comment]
说明所有IP都没有ping通......麻烦贴一下`log/ping.log`中的内容

**Comment by weihanmatt** [comment]
> 说明所有IP都没有ping通......麻烦贴一下`log/ping.log`中的内容

过了几天又试了一下可以了 已经下载慢速 感谢大佬！

**Comment by rinkky** [comment]
不客气~
