### ISSUE TITLE
UnboundLocalError: local variable 'start' referenced before assignment

### ISSUE THREAD

**Issue by zbttl** [rinkky/xbox-download-host#5]
运行环境是 win10 + python 3.7
测速过程中会在某些 ip 处停下并报错。
![image](https://user-images.githubusercontent.com/22035093/79012701-7c122c80-7b99-11ea-8464-ecb28c86f3bc.png)
我将项目 git clone 下来并在 `/xbox/__init__.py` 中将
```
start = time.clock()
```
改为
```        
global start 
start = time.clock()
```
似乎就能临时解决问题？

**Comment by rinkky** [comment]
确实是bug, 1.3.1版本已修复。
感谢反馈~
